# Configuration for automatic labeling of pull requests
# https://github.com/actions/labeler

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: ['docs/**/*', '*.md', 'README*']

# Source code changes
core:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*']

# Test changes
tests:
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.*', '**/*.spec.*', 'test/**/*', 'tests/**/*']

# Configuration changes
config:
  - changed-files:
    - any-glob-to-any-file: ['*.json', '*.js', '*.yml', '*.yaml', '.eslintrc*', '.prettier*', 'tsconfig*']

# CI/CD changes
ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package*.json', 'yarn.lock', 'pnpm-lock.yaml']

# Build system
build:
  - changed-files:
    - any-glob-to-any-file: ['webpack*', 'rollup*', 'vite*', 'esbuild*', 'tsup*']
