name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, Windows 10, macOS 12.0]
        - Node.js version: [e.g. 18.17.0]
        - Package version: [e.g. 1.0.0]
        - Database: [e.g. MongoDB 6.0]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here, including logs, screenshots, etc.
